##
## docker-compose.yml — определяет сервисы для разработки и тестирования.
#
#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432, 8080).
#  - Настроить volume для хранения данных БД.

services:
  server:
    build: server
    image: bank_rest
    container_name: bank_rest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/bank_rest
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345678

  db:
    image: postgres:16.1
    container_name: postgres_bank_rest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bank_rest
    volumes:
      - db-data:/lib/postgresql/data

volumes:
  db-data:
    driver: local

